### ISSUE TITLE
SSL not working with Firefox

### ISSUE THREAD

**Issue by kanlukasz** [leokhoa/laragon#152]
Hello,

I tried to create a simple blank website with https
Unfortunately, SSL does not work with Firefox (Chrome or Opera work correctly)

![obraz](https://user-images.githubusercontent.com/30685349/74829706-edf49500-5311-11ea-9578-697838314253.png)

---
I tried also:
![obraz](https://user-images.githubusercontent.com/30685349/74829741-fea50b00-5311-11ea-8c9b-a06568bdd0eb.png)
but still not working

---
What else should I check?

#### My Env:
- Win 10 Home: latest update
- Laragon Lite: latest version
- FF, Chrome, Opera: all latest version

---
Some screens (sorry it's in Polish language):
![obraz](https://user-images.githubusercontent.com/30685349/74829622-bab20600-5311-11ea-9d38-8592e705af60.png)

![obraz](https://user-images.githubusercontent.com/30685349/74829641-c4d40480-5311-11ea-8706-c01833142a31.png)

**Comment by Sotiris-k** [comment]
The answer is here: https://forum.laragon.org/topic/1355/quick-ssl-working-in-every-browser-except-for-firefox-any-help-is-appreciated-since-firefox-is-my-main-browser/2

- (1) In a new tab, type or paste about:config in the address bar and press Enter/Return. Click the button promising to be careful or accepting the risk.
- (2) In the search box above the list, type or paste enterp and pause while the list is filtered
- (3) Double-click the security.enterprise_roots.enabled preference to switch the value from false to true

**Comment by kanlukasz** [comment]
I think it can be interesting too:
https://blog.mozilla.org/security/2020/04/14/expanding-client-certificates-in-firefox-75/

**Comment by kanlukasz** [comment]
Another option is the external library, which I found:
https://github.com/FiloSottile/mkcert

**Comment by varunsridharan** [comment]
I am using mkcert it works great

Varun
+91 9042248903

**Comment by samjco** [comment]
Yes, it doesn't seem to work with Firefox :(

**Comment by kanlukasz** [comment]
Due to no response from the author I decide closing this issue as "wont-fix"

My advice to others:
- use mkcert
- learn and start using WSL2
- https://blog.mozilla.org/security/2020/04/14/expanding-client-certificates-in-firefox-75/
- https://wiki.mozilla.org/CA/AddRootToFirefox

Good luck

**Comment by leokhoa** [comment]
@kanlukasz : I thought Sotiris-k answered you.
Anyway, good luck!
