### ISSUE TITLE
Apache is Working But MySQL Hangs/Freezes on Initializing Data

### ISSUE THREAD

**Issue by chytons** [leokhoa/laragon#798]
### Discussed in https://github.com/leokhoa/laragon/discussions/797

<div type='discussions-op-text'>

<sup>Originally posted by **chytons** June  5, 2024</sup>
Good day,
I installed Laragon v6 and having trouble starting MySQL server.
When I click on Start All, Apache starts immediately but MySQL freezes on Initializing data.
I have installed in the default location and also other locations without success.
Below are the details of my environment:

OS - Windows 10 22H2 Build 19045.4474
RAM - 32 GB

Funny enough, I have another PC with similar configuration and everything is working fine on it.

![laragon-screen-capture](https://github.com/leokhoa/laragon/assets/53003784/06ccafde-352a-4fd1-a805-edf08826200c)

</div>

**Comment by LebToki** [comment]
Do you happen to have another mysql server running ?
from a previous installation ?
have you tried giving MySQL a non-standard port to see if it loads ?
if you happen to have a previous installation i would suggest you move your data to this one and delete the previous installation

**Comment by chytons** [comment]
I have portable version of XAMPP on my system. I start/stop Apache and MySQL manually. Neither XAMPP's Apache nor MySQL was running while troubleshooting Laragon issue. I have changed the folder path where XAMPP is installed in case of conflict. I have completely removed XAMPP using Revo UninstallerPro tool, but a reference is being made to the delete location of XAMPP installation. I have also changed MySQL port to 3406. I have given full control permission on C:\laragon to Authenticated Users and Users.
I set up two Windows 10 VMs and laragon installations in them are working. I copied the mysql-8 folder from one of the VM into the same location of my system. MySQL started running but exited with error after some seconds. I have attached all the relevant screen captures here.

[mysql_error.log](https://github.com/user-attachments/files/15676244/mysql_error.log)

![laragon-mysql-error](https://github.com/leokhoa/laragon/assets/53003784/a2bdbdd1-ee31-4d4e-aefc-81211cf22083)


https://github.com/leokhoa/laragon/assets/53003784/efef32e9-a3e3-4b94-930c-69cf8057e19a

**Comment by LebToki** [comment]
Hi @chytons,

I reviewed the logs you provided, and it appears that MySQL is unable to use the designated data directory C:\\laragon\\data\\mysql-8\\. Here are a few steps you can take to troubleshoot and resolve this issue:

**Check Directory Permissions:**
Ensure that the C:\\laragon\\data\\mysql-8\\ directory has the correct permissions. The MySQL server needs read/write access to this directory.

**Check Directory Path:**
Verify that the directory path C:\\laragon\\data\\mysql-8\\ exists and is correct. If there were any typos or changes in the path, MySQL would not be able to access it.

**Check Ownership:**
Make sure the MySQL process has ownership of the C:\\laragon\\data\\mysql-8\\ directory. The directory should be owned by the same user account that runs the MySQL server.

**Remove Corrupted Files:**
The log suggests removing all files that the server added to the directory. It might be helpful to back up any important data and then remove or rename the C:\\laragon\\data\\mysql-8\\ directory. Afterward, restart the MySQL server to see if it creates a new data directory.

**Check MySQL Configuration:**
Review the MySQL configuration file (my.ini or my.cnf) to ensure that the data directory is correctly specified.

**Port Configuration:**
Since you mentioned changing the MySQL port to 3406, ensure that this change is also reflected in the MySQL configuration file and that no other processes are using this port.

**Clean Installation:**
If the issue persists, consider performing a clean installation of Laragon and MySQL. Ensure that no remnants of previous installations are causing conflicts.

I hope these steps help resolve the issue. If you need further assistance, feel free to reach out.

Best regards,
[Tarek] or @LebToki

**Comment by LebToki** [comment]
Do me and yourself a favor!
can you check Task Manager and search for MySQLd (is it running ?)
it could be that you had Xampp installed with persistant services (auto Starting on their own with Windows)
for the sake to finding if this is true in your case .
End the service ---
--------------------Run MySQL in Laragon
if this works then we have to find a way to remove your redundant MySQL server/service

**Comment by LebToki** [comment]
```[sh]
@echo off
cd /D %~dp0

echo Shutting down MySQL...

REM Check if mysqld.exe is running and kill the process
tasklist /FI "IMAGENAME eq mysqld.exe" 2>NUL | find /I /N "mysqld.exe">NUL
if "%ERRORLEVEL%"=="0" (
    echo mysqld.exe found, terminating process...
    taskkill /F /IM mysqld.exe
) else (
    echo mysqld.exe not found, skipping process termination.
)

REM Check for MySQL installation directory
if exist "C:\xampp\mysql\data" (
    set MYSQL_DIR=C:\xampp\mysql\data
) else if exist "D:\xampp\mysql\data" (
    set MYSQL_DIR=D:\xampp\mysql\data
) else (
    echo MySQL installation directory not found in default locations.
    goto exit
)

echo MySQL installation directory found at %MYSQL_DIR%.

REM Remove auto-run service request from XAMPP
echo Disabling MySQL service auto-start in XAMPP...
sc config MySQL start= disabled
if "%ERRORLEVEL%"=="0" (
    echo MySQL service auto-start disabled successfully.
) else (
    echo Failed to disable MySQL service auto-start.
)

:exit
echo Operation completed.
pause
```

### Explanation:

# Shutting down MySQL:

- Uses tasklist to check if mysqld.exe is running.
- Uses taskkill to terminate mysqld.exe if it is found running.

# Check for MySQL installation directory:

- Checks if C:\xampp\mysql\data or D:\xampp\mysql\data exists.
- Sets the MYSQL_DIR variable to the detected directory.

#  Remove auto-run service request from XAMPP:

- Uses sc config to disable the MySQL service from starting automatically.

# Usage:

- Save the above code as mysql_cleanup.bat.

Just Remember to run the batch file as an administrator.

**Comment by chytons** [comment]
> Hi @chytons,
> 
> I reviewed the logs you provided, and it appears that MySQL is unable to use the designated data directory C:\laragon\data\mysql-8\. Here are a few steps you can take to troubleshoot and resolve this issue:
> 
> **Check Directory Permissions:** Ensure that the C:\laragon\data\mysql-8\ directory has the correct permissions. The MySQL server needs read/write access to this directory.
> 
> **Check Directory Path:** Verify that the directory path C:\laragon\data\mysql-8\ exists and is correct. If there were any typos or changes in the path, MySQL would not be able to access it.
> 
> **Check Ownership:** Make sure the MySQL process has ownership of the C:\laragon\data\mysql-8\ directory. The directory should be owned by the same user account that runs the MySQL server.
> 
> **Remove Corrupted Files:** The log suggests removing all files that the server added to the directory. It might be helpful to back up any important data and then remove or rename the C:\laragon\data\mysql-8\ directory. Afterward, restart the MySQL server to see if it creates a new data directory.
> 
> **Check MySQL Configuration:** Review the MySQL configuration file (my.ini or my.cnf) to ensure that the data directory is correctly specified.
> 
> **Port Configuration:** Since you mentioned changing the MySQL port to 3406, ensure that this change is also reflected in the MySQL configuration file and that no other processes are using this port.
> 
> **Clean Installation:** If the issue persists, consider performing a clean installation of Laragon and MySQL. Ensure that no remnants of previous installations are causing conflicts.
> 
> I hope these steps help resolve the issue. If you need further assistance, feel free to reach out.
> 
> Best regards, [Tarek] or @LebToki

@LebToki,
After going through the steps, you provided above, it occurred to me that I have an old my.cnf  file directly on my C:\ drive which was pointing to XAMPP installation path. This was always read every time I started MySQL server.
After renaming the file, the issue disappeared like magic.

Thanks for all the assistance.
